# Generated by Django 3.1.2 on 2020-11-04 01:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MinesweeperGame',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('board', models.TextField(verbose_name='board')),
                ('rows', models.SmallIntegerField(verbose_name='rows')),
                ('columns', models.SmallIntegerField(verbose_name='columns')),
                ('mines', models.SmallIntegerField(verbose_name='mines')),
                ('start_at', models.DateTimeField(auto_now=True, verbose_name='start_at')),
                ('finish_at', models.DateTimeField(null=True, verbose_name='finish_at')),
                ('status', models.SmallIntegerField(choices=[(1, 'STARTED'), (2, 'FINISHED')], default=1, verbose_name='status')),
                ('result', models.SmallIntegerField(choices=[(1, 'WIN'), (2, 'LOST')], null=True, verbose_name='result')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'minesweeper game',
                'verbose_name_plural': 'minesweeper games',
            },
        ),
    ]
